/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class okcoin_oklink_liblink_MyClass */

#ifndef _Included_okcoin_oklink_liblink_MyClass
#define _Included_okcoin_oklink_liblink_MyClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     okcoin_oklink_liblink_MyClass
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_okcoin_oklink_liblink_MyClass_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
